trigger/S3_TO_ADLS_KR_OTC_INV_ETL_FRAMEWORK_trigger.json
trigger/S3_TO_ADLS_POP6_MASTER_TRASACTION_trigger.json
trigger/S3_TO_ADLS_TW_IMS_DISTRIBUTOR_trigger.json
trigger/s3_to_adls_j_tw_sell_in_forecast_transaction_data_ingestion_trigger.json

S3 TO ADLS North Asia triggers

S3 TO ADLS North Asia Triggers

---

trigger/S3_TO_ADLS_JPN_POS_LOAD_trigger.json

trigger: S3_TO_ADLS_JPN_POS_LOAD_trigger

trigger: S3_TO_ADLS_JPN_POS_LOAD_trigger

---

trigger/s3_to_adls_JP_DCL_GENERIC_EXTRACTION_FILESETUP_trigger.json
trigger/s3_to_adls_JP_DCL_MYKOKYA_trigger.json
trigger/s3_to_adls_JP_DCL_RAKUTEN_trigger.json

s3_to_adls trigger : japan dcl

s3_to_adls trigger : japan dcl

---

trigger/Historical_load_IND_RE.json

Updating trigger: Historical_load_IND_RE

---

trigger/Historical_load_IND_RE.json

Adf2 feature july release

---

linkedService/adfadbplt001lsmftappvkenvuecomjpdcl.json

Adding linkedService: adfadbplt001lsmftappvkenvuecomjpdcl

Adding linkedService: adfadbplt001lsmftappvkenvuecomjpdcl

---

publish_config.json

update from main

---

trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_5PS.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_ALTERYX.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_POS.json

Tmp kvadls to s3 sync fix IDN

---

trigger/EVT_TMP_KVADLS_TO_JJS3_RG_travel_retail.json

Tmp kvadls to s3 sync - update RG

Tmp kvadls to s3 sync - update RG 

---

trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_sellout.json

Tmp kvadls to s3 sync - update MYS

Tmp kvadls to s3 sync - update MYS

---

pipeline/PL_KVADLS_TO_JJS3.json

Tmp kvadls to s3 sync - fix concurrent and queuing issue

Tmp kvadls to s3 sync - fix concurrent and queuing issue

---

pipeline/PL_KVADLS_TO_JJS3.json

Tmp kvadls to s3 sync - fix concurrency

Tmp kvadls to s3 sync - fix concurrency

---

pipeline/PL_KVADLS_TO_JJS3.json

Tmp kvadls to s3 sync - fix threading

Tmp kvadls to s3 sync - fix threading

---

pipeline/PL_KVADLS_TO_JJS3.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_IVY.json

Tmp kvadls to s3 sync - add IDN IVY

Tmp kvadls to s3 sync - add IDN IVY

---

trigger/EVT_TMP_KVADLS_TO_JJS3_THA_ACCONVENDOR.json

Tmp kvadls to s3 sync

---

trigger/Historical_Trigger_Customer360.json

Updating trigger: Historical_Trigger_Customer360

---

trigger/EVT_TMP_KVADLS_TO_JJS3_THA_ACCONVENDOR.json
trigger/Historical_Trigger_Customer360.json

merge main to tmp

---

pipeline/PL_KVADLS_TO_JJS3.json
pipeline/PL_KVADLS_TO_JJS3_VNM.json

Tmp kvadls to s3 sync - add error reporting

Tmp kvadls to s3 sync - add error reporting

---

pipeline/PL_KVADLS_TO_JJS3.json
pipeline/PL_KVADLS_TO_JJS3_VNM.json

Tmp kvadls to s3 sync - fix reporting

Tmp kvadls to s3 sync - fix reporting

---

.github/workflows/main.yml

Tmp kvadls to s3 sync - add lower env stop triggers

Tmp kvadls to s3 sync - add lower env stop triggers

---

.github/workflows/main.yml

Update main.yml - fix CICD

---

pipeline/PL_KVADLS_TO_JJS3.json
pipeline/PL_KVADLS_TO_JJS3_VNM.json

Tmp kvadls to s3 sync - add concurrency timeout

Tmp kvadls to s3 sync - add concurrency timeout

---

trigger/EVT_TMP_KVADLS_TO_JJS3_HKG_Users.json
trigger/EVT_TMP_KVADLS_TO_JJS3_HKG_WINGKEUNG.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_5PS.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_ALTERYX.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_IVY.json
trigger/EVT_TMP_KVADLS_TO_JJS3_IDN_POS.json
trigger/EVT_TMP_KVADLS_TO_JJS3_KOR_NAVER.json
trigger/EVT_TMP_KVADLS_TO_JJS3_PAC_CBG.json
trigger/EVT_TMP_KVADLS_TO_JJS3_PAC_IRI_Scan_Data.json
trigger/EVT_TMP_KVADLS_TO_JJS3_PAC_Pacific_reg_inv.json
trigger/EVT_TMP_KVADLS_TO_JJS3_PAC_ap_perenso.json
trigger/EVT_TMP_KVADLS_TO_JJS3_PAC_pharm_ecommerce.json
trigger/EVT_TMP_KVADLS_TO_JJS3_RG_travel_retail.json
trigger/EVT_TMP_KVADLS_TO_JJS3_SGP_SCAN360.json
trigger/EVT_TMP_KVADLS_TO_JJS3_THA_ACCONVENDOR.json
trigger/EVT_TMP_KVADLS_TO_JJS3_TW_JW.json
trigger/EVT_TMP_KVADLS_TO_JJS3_VNM_DKSH.json
trigger/EVT_TMP_KVADLS_TO_JJS3_VNM_HQSOFT.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_instoreexecution.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_master_sellin.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_others_sellin.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_pos.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_sellout.json
trigger/EVT_TMP_KVADLS_TO_JJS3__malaysia_prod_targets_sellin.json
trigger/EVT_TMP_KVADLS_TO_JJS3__philippines_prod_acommerce_gmv.json
trigger/EVT_TMP_KVADLS_TO_JJS3__thailand_prod_TH_MT.json
trigger/EVT_TMP_KVADLS_TO_JJS3__thailand_prod_perfectstore_consumerreach_711.json
trigger/EVT_TMP_KVADLS_TO_JJS3__thailand_prod_perfectstore_consumerreach_cvs.json

Tmp kvadls to s3 sync - pause all event syncs

Tmp kvadls to s3 sync - pause all event syncs
